import { FamilyInviteStatus, FamilyMemberRole, FamilyMembershipStatus, NotificationType } from '@prisma/client';
import type { FamilyRepository } from '../../../application/ports/outbound/family-repository.js';
import type { NotificationRepository } from '../../../application/ports/outbound/notification-repository.js';
import type { FamilyInvite, FamilyView } from '../../../domain/family/family.js';
import { prisma } from './prisma-client.js';
const memberInclude = { memberships: { where: { status: FamilyMembershipStatus.ACTIVE }, include: { user: { select: { id: true, firstName: true, lastName: true } } }, orderBy: { joinedAt: 'asc' as const } } };
const mapFamily = (group: any): FamilyView => ({ id: group.id, name: group.name, members: group.memberships.map((m: any) => ({ userId: m.userId, firstName: m.user.firstName, lastName: m.user.lastName, role: m.role, status: m.status, joinedAt: m.joinedAt })) });
const mapInvite = (invite: any): FamilyInvite => ({ id: invite.id, familyGroupId: invite.familyGroupId, inviterId: invite.inviterId, inviteeId: invite.inviteeId, inviteeEmail: invite.inviteeEmail, status: invite.status, createdAt: invite.createdAt });
export class PrismaFamilyRepository implements FamilyRepository {
  async getActiveFamily(userId: number) { const member = await prisma.familyMembership.findFirst({ where: { userId, status: FamilyMembershipStatus.ACTIVE, familyGroup: { status: 'ACTIVE', deletedAt: null } }, select: { familyGroupId: true } }); if (!member) return null; const group = await prisma.familyGroup.findUnique({ where: { id: member.familyGroupId }, include: memberInclude }); return group ? mapFamily(group) : null; }
  async getActiveMembership(userId: number) { return prisma.familyMembership.findFirst({ where: { userId, status: FamilyMembershipStatus.ACTIVE, familyGroup: { status: 'ACTIVE', deletedAt: null } }, select: { familyGroupId: true, role: true } }); }
  async createGroup(owner: { id: number; firstName: string }, now: Date) { const group = await prisma.familyGroup.create({ data: { name: `Família de ${owner.firstName}`, memberships: { create: { userId: owner.id, role: FamilyMemberRole.OWNER, status: FamilyMembershipStatus.ACTIVE, joinedAt: now } } }, include: memberInclude }); return mapFamily(group); }
  async createInvite(data: { familyGroupId: number; inviterId: number; inviteeId: number; inviteeEmail: string }) { return mapInvite(await prisma.familyInvite.create({ data: { ...data, status: FamilyInviteStatus.PENDING } })); }
  async findInvite(id: number, inviteeId: number) { const invite = await prisma.familyInvite.findFirst({ where: { id, inviteeId } }); return invite ? mapInvite(invite) : null; }
  async hasPendingInvite(inviteeId: number) { return Boolean(await prisma.familyInvite.findFirst({ where: { inviteeId, status: FamilyInviteStatus.PENDING }, select: { id: true } })); }
  async listReceivedInvites(userId: number) { return (await prisma.familyInvite.findMany({ where: { inviteeId: userId, status: FamilyInviteStatus.PENDING }, orderBy: { createdAt: 'desc' } })).map(mapInvite); }
  async acceptInvite(invite: FamilyInvite, now: Date) { await prisma.$transaction([prisma.familyInvite.update({ where: { id: invite.id }, data: { status: FamilyInviteStatus.ACCEPTED, respondedAt: now } }), prisma.familyMembership.upsert({ where: { familyGroupId_userId: { familyGroupId: invite.familyGroupId, userId: invite.inviteeId } }, create: { familyGroupId: invite.familyGroupId, userId: invite.inviteeId, role: FamilyMemberRole.MEMBER, status: FamilyMembershipStatus.ACTIVE, joinedAt: now }, update: { status: FamilyMembershipStatus.ACTIVE, role: FamilyMemberRole.MEMBER, joinedAt: now, leftAt: null } })]); }
  async declineInvite(invite: FamilyInvite, now: Date) { await prisma.familyInvite.update({ where: { id: invite.id }, data: { status: FamilyInviteStatus.DECLINED, respondedAt: now } }); }
  async leave(userId: number, now: Date) { await prisma.familyMembership.updateMany({ where: { userId, status: FamilyMembershipStatus.ACTIVE }, data: { status: FamilyMembershipStatus.LEFT, leftAt: now } }); }
  async remove(ownerId: number, memberUserId: number, now: Date) { const owner = await this.getActiveMembership(ownerId); if (!owner || owner.role !== 'OWNER') return false; const result = await prisma.familyMembership.updateMany({ where: { familyGroupId: owner.familyGroupId, userId: memberUserId, status: FamilyMembershipStatus.ACTIVE, role: FamilyMemberRole.MEMBER }, data: { status: FamilyMembershipStatus.REMOVED, leftAt: now } }); return result.count > 0; }
  async dissolve(ownerId: number, now: Date) { const owner = await this.getActiveMembership(ownerId); if (!owner || owner.role !== 'OWNER') return []; const active = await prisma.familyMembership.findMany({ where: { familyGroupId: owner.familyGroupId, status: FamilyMembershipStatus.ACTIVE }, select: { userId: true } }); await prisma.$transaction([prisma.familyGroup.update({ where: { id: owner.familyGroupId }, data: { status: 'DISSOLVED', deletedAt: now } }), prisma.familyMembership.updateMany({ where: { familyGroupId: owner.familyGroupId, status: FamilyMembershipStatus.ACTIVE }, data: { status: FamilyMembershipStatus.LEFT, leftAt: now } }), prisma.familyInvite.updateMany({ where: { familyGroupId: owner.familyGroupId, status: FamilyInviteStatus.PENDING }, data: { status: FamilyInviteStatus.CANCELLED, respondedAt: now } })]); return active.map((entry) => entry.userId); }
  async activeMemberUserIds(userId: number) { const family = await this.getActiveFamily(userId); return family?.members.map((member) => member.userId) ?? null; }
}
export class PrismaNotificationRepository implements NotificationRepository {
  async create(data: { userId: number; type: any; title: string; body: string; payload?: unknown }) { await prisma.notification.create({ data: { ...data, type: data.type as NotificationType, payload: data.payload as any } }); }
  async list(userId: number, unreadOnly?: boolean) { return prisma.notification.findMany({ where: { userId, ...(unreadOnly ? { readAt: null } : {}) }, orderBy: { createdAt: 'desc' } }); }
  async markRead(userId: number, id: number, now: Date) { return (await prisma.notification.updateMany({ where: { id, userId, readAt: null }, data: { readAt: now } })).count > 0; }
  async markAllRead(userId: number, now: Date) { await prisma.notification.updateMany({ where: { userId, readAt: null }, data: { readAt: now } }); }
}
