import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { config } from './shared/config';
import { errorHandler } from './shared/http';
import authRoutes from './modules/auth/routes';
import categoriesRoutes from './modules/categories/routes';
import transactionsRoutes from './modules/transactions/routes';
import dashboardRoutes from './modules/dashboard/routes';
import usersRoutes from './modules/users/routes';
import { authenticate } from './shared/middleware/authenticate';

const app = express();
app.use(cors({ origin: config.frontendOrigins, credentials: false }));
app.use(express.json({ limit: '1mb' }));
app.get('/health', (_req, res) => res.json({ status: 'ok', timestamp: new Date().toISOString() }));
app.use('/api/auth', authRoutes);
app.use('/api/categories', authenticate, categoriesRoutes);
app.use('/api/transactions', authenticate, transactionsRoutes);
app.use('/api/dashboard', authenticate, dashboardRoutes);
app.use('/api/users', authenticate, usersRoutes);
app.use((_req, res) => res.status(404).json({ code: 'NOT_FOUND', message: 'Rota não encontrada.' }));
app.use(errorHandler);
app.listen(config.port, () => console.info(`API disponível em http://localhost:${config.port}`));
