'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FormEvent, useState } from 'react';
import { z } from 'zod';
import { services, ApiError } from '../../lib/api';
import { Feedback } from '../../components/Feedback';

const schema = z.object({ firstName: z.string().min(1, 'Informe seu nome.'), lastName: z.string().min(1, 'Informe seu sobrenome.'), email: z.string().email('Informe um email válido.'), phone: z.string().min(8, 'Informe um telefone válido.'), password: z.string().min(8, 'A senha deve ter 8 caracteres ou mais.'), confirmPassword: z.string() }).refine((data) => data.password === data.confirmPassword, { path: ['confirmPassword'], message: 'As senhas não coincidem.' });
export default function RegisterPage() { const router = useRouter(); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); const raw = Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>; const check = schema.safeParse(raw); if (!check.success) return setError(check.error.issues[0].message); setPending(true); try { await services.register(check.data); router.replace('/login?registered=1'); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Não foi possível criar sua conta.'); } finally { setPending(false); } }
  return <main className="auth-page"><aside className="auth-aside"><div className="brand"><span className="brand-mark">$</span> Financial Control</div><div><h1>Comece pelo que importa para você.</h1><p>Seu histórico fica separado e acessível somente na sua conta.</p></div><small>Dados financeiros organizados, sem complicação.</small></aside><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><h2>Crie sua conta</h2><p>Preencha os dados abaixo para começar.</p><Feedback error={error} /><div className="fields-two"><div className="field"><label htmlFor="firstName">Nome</label><input id="firstName" name="firstName" /></div><div className="field"><label htmlFor="lastName">Sobrenome</label><input id="lastName" name="lastName" /></div></div><div className="field"><label htmlFor="email">Email</label><input id="email" name="email" type="email" /></div><div className="field"><label htmlFor="phone">Telefone</label><input id="phone" name="phone" inputMode="tel" placeholder="(11) 99999-9999" /></div><div className="fields-two"><div className="field"><label htmlFor="password">Senha</label><input id="password" name="password" type="password" autoComplete="new-password" /></div><div className="field"><label htmlFor="confirmPassword">Confirmar senha</label><input id="confirmPassword" name="confirmPassword" type="password" autoComplete="new-password" /></div></div><button className="primary" disabled={pending}>{pending ? 'Criando…' : 'Criar conta'}</button><p className="form-foot">Já possui conta? <Link className="link" href="/login">Entrar</Link></p></form></section></main>; }
